### ISSUE TITLE
Add support for korabli

### ISSUE THREAD

**Issue by zfxsquare** [AndrewTaro/PenetrationCalculatorPublic#1]
Is it possible to add support for korabli, currently it doesn't work in game

**Comment by AndrewTaro** [comment]
> Is it possible to add support for korabli, currently it doesn't work in game

No, the mod is specifically designed for the WG client, and has been approved only by WG.

It was before the company split, but Lesta rejected this idea. Thus, it is prohibited to use even if it worked.

**Comment by zfxsquare** [comment]
Understood, thank you for developing this plugin!
